### ISSUE TITLE
On Login Api Issue

### ISSUE THREAD

**Issue by pratikg17** [marley-nodejs/Build-a-Real-Time-web-app-in-node.js-Angular.js-mongoDB#1]
Error: Uncaught, unspecified "error" event. (Incorrect arguments)
    at Function.emit (events.js:163:17)
    at Immediate.<anonymous> (E:\NodeTest\userstory\node_modules\mongoose\lib\query.js:2322:23)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

**Comment by webmakaka** [comment]
Ok. I'll check this error on holidays.

**Comment by webmakaka** [comment]
Hi, pratikg17!
I run this application and do not receive this error.

![issue_01](https://cloud.githubusercontent.com/assets/10372159/20652853/bcc75882-b512-11e6-9f11-80180024a0d8.png)

You can write more detailed information about error if it important for you.
But it is a old project and i do not want to work with him.

**Comment by pratikg17** [comment]
It was a version issue of  jsonwebtoken
